apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

# You will need to delete storageclass to update this field
# provisioner: csi-rclone
# parameters:
#   exposeRc: "true"
#   pathPattern: "${.PVC.namespace}/${.PVC.annotations.csi-rclone/storage-path}"